import type { Metadata } from "next";
import SessionProvider from "providers/SessionProvider";
import localFont from "next/font/local";
import { Toaster } from 'sonner';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <SessionProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
          <Toaster position="bottom-right" closeButton duration={5000} />
        </body>
      </SessionProvider>
    </html>
  );
}
